package com.aehooo.tdsqn.resources;

public enum TextureName {
	MAPA1_BG, BARRA_LATERAL, ZOMBIE, GROUP, TIRO, BUTTON, LOST, MENU_SUPERIOR, HEALER, REI, DPS, SUPPORT, TANK, TORRE_BANANA, TORRE_MELANCIA;
}
